# TODO License.

# Configuration for the JAVA LSP server component
---

version: +
repository_root: "https://lsp-component-java-0-12-1.cfapps.eu10.hana.ondemand.com"

env:
    workdir: language_server_bin_exec_jdt/
    exec: language_server_bin_exec_jdt/launcher.sh
    ipc:
        protocol: "stream"
