# TODO License.

# Configuration for the JAVA LSP server component
---
version: 0.0.+
repository_root: "https://lsp-component-java-001.cfapps.eu10.hana.ondemand.com/"
env:
    workdir: language_server_bin_exec_jdt/
    exec: language_server_bin_exec_jdt/launcher.sh
    STDIN_PORT: 8990
    STDOUT_PORT: 8991
    ipc:
        protocol: socket
        inport: 8991
        outport: 8990
